pip install pbr
pip install eventlet
pip install oslo_i18n
pip install oslo_config
pip install oslo_concurrency
pip install oslo_log
pip install oslo_messaging
pip install pecam
pip install pecan
pip install keystoneauth1
pip install os_resource_classes
pip install oslo_db
pip install python-openstackclient
pip install oslo_versionedobjects
pip install keystonemiddleware
pip install wsme
pip install microversion_parse
pip install oslo_policy
pip install oslo_privsep